name: Pull Request

permissions: {}

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de
        with:
          toolchain: stable

      - run: cargo --version

      - name: Run tests
        run: cargo test --verbose --no-fail-fast ${{ runner.os == 'macOS' && '-- --test-threads=1' || '' }}

  miri:
    name: Miri
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de
        with:
          toolchain: nightly
          components: "miri"

      - run: cargo --version

      - name: Run miri test
        run: cargo miri test

  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de
        with:
          toolchain: nightly
          components: "rustfmt"

      - run: cargo --version

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de
        with:
          toolchain: "stable"
          components: "clippy"

      - name: Check Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

  docs:
    name: Docs
    runs-on: "ubuntu-latest"
    env:
      # deny rustdoc warnings
      RUSTDOCFLAGS: -D warnings
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de
        with:
          toolchain: stable

      - run: cargo --version

      - name: Check docs
        run: cargo doc --verbose --all-features --no-deps
